import Foundation
import EventKit
import MemoryKit

#if canImport(FoundationModels)
import FoundationModels
#endif

// MARK: - Onboarding magic moment (§Phase 8)
//
// Cold-start credibility is existential for a personalization product: if day one feels generic,
// the user churns before the memory loop ever pays off. So right after onboarding we run a single
// on-device pass over data **already on the device** (today's calendar + reminders) to surface one
// strikingly relevant observation — a "this already gets me" moment — before any conversation.
//
// Privacy first (§B): access is requested **progressively and value-framed** (the UI explains why
// before this runs), the read is on-device, and the observation is generated by the local model.
// Nothing leaves the device. If access is denied or the day is empty, it degrades silently.

@MainActor
public enum MagicMomentService {

    public struct AccessResult: Sendable {
        public let calendarGranted: Bool
        public let remindersGranted: Bool
        public var anyGranted: Bool { calendarGranted || remindersGranted }
    }

    /// Request read access to calendar + reminders. Call only after the UI has framed the value.
    public static func requestAccess() async -> AccessResult {
        let store = EKEventStore()
        let calendar = (try? await store.requestFullAccessToEvents()) ?? false
        let reminders = (try? await store.requestFullAccessToReminders()) ?? false
        return AccessResult(calendarGranted: calendar, remindersGranted: reminders)
    }

    /// Read today's already-available data and produce one warm, specific observation entirely
    /// on-device. Returns nil when there's nothing useful to say or the model is unavailable.
    public static func generateObservation(persona: Persona?) async -> String? {
        let digest = await gatherTodayDigest()
        guard !digest.isEmpty else { return nil }

        guard AvailabilityService().isAvailable else { return nil }

#if canImport(FoundationModels)
        let name = persona?.name ?? "your assistant"
        let instructions = """
        You are \(name), greeting the user for the very first time. From the snapshot of their day \
        below, make ONE warm, specific, genuinely useful observation or offer — proof you already \
        get them. One or two sentences, conversational, no lists, no preamble, no markdown. If the \
        data is thin, speak to the most concrete item. Never invent details that aren't present.
        """
        let session = LanguageModelSession(instructions: instructions)
        do {
            let response = try await session.respond(
                to: "Here's their day:\n\(digest)",
                options: GenerationOptions(temperature: 0.6)
            )
            let text = response.content.trimmingCharacters(in: .whitespacesAndNewlines)
            return text.isEmpty ? nil : text
        } catch {
            return nil
        }
#else
        return nil
#endif
    }

    // MARK: - Gathering today's data

    private static func gatherTodayDigest() async -> String {
        let store = EKEventStore()
        var lines: [String] = []
        let calendar = Calendar.current
        let now = Date()
        let startOfDay = calendar.startOfDay(for: now)
        let endOfDay = calendar.date(byAdding: .day, value: 1, to: startOfDay) ?? now

        if EKEventStore.authorizationStatus(for: .event) == .fullAccess {
            let predicate = store.predicateForEvents(withStart: now, end: endOfDay, calendars: nil)
            for event in store.events(matching: predicate).prefix(6) {
                let time = event.startDate.formatted(date: .omitted, time: .shortened)
                lines.append("• \(time): \(event.title ?? "Event")")
            }
        }

        if EKEventStore.authorizationStatus(for: .reminder) == .fullAccess {
            for title in await fetchReminderTitles(store: store, end: endOfDay).prefix(6) {
                lines.append("• Reminder: \(title)")
            }
        }

        guard !lines.isEmpty else { return "" }
        return "Today is \(now.formatted(date: .complete, time: .omitted)).\n" + lines.joined(separator: "\n")
    }

    /// Fetch incomplete reminders due by `end`, returning only their titles so the result is
    /// `Sendable` across the continuation boundary (EKReminder is not).
    private static func fetchReminderTitles(store: EKEventStore, end: Date) async -> [String] {
        let predicate = store.predicateForIncompleteReminders(
            withDueDateStarting: nil,
            ending: end,
            calendars: nil
        )
        return await withCheckedContinuation { continuation in
            store.fetchReminders(matching: predicate) { reminders in
                let titles = (reminders ?? []).compactMap { $0.title }
                continuation.resume(returning: titles)
            }
        }
    }
}
